const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmtHash=v=>{v=Number(v||0);const u=["H/s","kH/s","MH/s","GH/s","TH/s","PH/s"];let i=0;while(v>=1000&&i<u.length-1){v/=1000;i++}return `${v.toFixed(v>=100?0:2)} ${u[i]}`};
const fmtDiff=v=>{v=Number(v||0);const u=["","K","M","G","T","P"];let i=0;while(v>=1000&&i<u.length-1){v/=1000;i++}return `${v.toFixed(v>=100?0:2)}${u[i]}`};
const ago=v=>{if(!v)return"Never";let d=new Date(v);if(!isNaN(Number(v)))d=new Date(Number(v)*1000);const s=Math.max(0,(Date.now()-d)/1000);if(s<60)return`${Math.floor(s)}s ago`;if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return d.toLocaleDateString()};
let state={};

function route(){const id=(location.hash||"#overview").slice(1);$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav a').forEach(x=>x.classList.toggle('active',x.hash===`#${id}`))}
window.addEventListener('hashchange',route);route();

function render(s){state=s;const pool=s.pool||{},node=s.node||{},both=pool.online&&node.online;$('#health').className=`health ${both?'good':'bad'}`;$('#health span').textContent=both?'Pool + node online':pool.online?'Node unavailable':'Pool unavailable';
 const synced=node.online&&!node.initialBlockDownload&&Number(node.verificationProgress||0)>.9999;
 $('#metrics').innerHTML=[['Share-estimated hashrate',fmtHash(s.totalHashRate),'Fresh active-worker estimate'],['Workers',s.totalMiners||0,`${(s.workers||[]).length} active sessions`],['Block height',s.blockHeight||'—',synced?'Node synchronized':'Checking node sync'],['Candidates',(s.candidates||[]).length,'Proof checked locally'],['Bitcoin Core',node.online?'Online':'Offline',node.subversion||node.error||'RPC unavailable']].map((m,i)=>`<article class="metric"><label>${m[0]}</label><strong class="${i===4?(node.online?'good-text':'bad-text'):''}">${esc(m[1])}</strong><small>${esc(m[2])}</small></article>`).join('');
 renderWorkers(s.workers||[]);renderBlocks(s.candidates||[]);renderEvents(s.events||[]);renderConnection(s.connection||{});loadChart();
}
function renderWorkers(items){$('#workers-list').innerHTML=items.length?items.map(w=>`<article class="worker"><header><i class="dot"></i><div><strong>${esc(w.clientName)}</strong><small>${esc(w.address)}</small></div><span class="badge">${esc(w.userAgent||'Stratum V1')}</span></header><strong class="worker-hash">${fmtHash(w.hashRate)}</strong><dl><div><dt>Best difficulty</dt><dd>${fmtDiff(w.bestDifficulty)}</dd></div><div><dt>Last seen</dt><dd>${ago(w.updatedAt)}</dd></div><div><dt>Session</dt><dd>${esc(w.sessionId)}</dd></div><div><dt>Started</dt><dd>${ago(w.startTime)}</dd></div></dl></article>`).join(''):'<div class="empty">No worker sessions yet. Open Connect for the Stratum settings.</div>'}
function renderBlocks(items){$('#blocks-list').innerHTML=items.length?items.map(b=>`<article class="block-card"><div class="block-icon">₿</div><div><p class="eyebrow">Height ${esc(b.height)} · ${esc(b.worker)}</p><h2>${b.proof_valid?'Proof verified':'Invalid candidate proof'}</h2><code title="${esc(b.block_hash)}">${esc(b.block_hash)}</code></div><div class="block-stat"><label>Confirmations</label><strong>${b.confirmations??'Pending'}</strong></div><div><span class="status"><i class="${esc(b.status)}"></i>${esc(b.status)}</span></div></article>`).join(''):'<div class="empty">No network-target candidates recorded. The verifier is armed and watching Public Pool’s ledger.</div>'}
function renderEvents(items){$('#events').innerHTML=items.length?items.map(e=>`<div class="event"><time>${new Date(e.created_at*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><b class="${esc(e.level)}">${esc(e.kind)}</b><span>${esc(e.message)}</span></div>`).join(''):'<div class="empty">The system journal is quiet.</div>'}
function renderConnection(c){const local=`${c.localHost||'umbrel.local'}:${c.port||3333}`,pub=c.publicHost?`${c.publicHost}:${c.port||3333}`:'Not configured';$('#local-endpoint').textContent=local;$('#public-endpoint').textContent=pub;$('#recipe-host').textContent=c.publicHost||c.localHost||'umbrel.local';$('#recipe-port').textContent=c.port||3333}
async function loadChart(){try{const rows=await fetch('/api/history?hours=24').then(r=>r.json());drawChart(rows)}catch{}}
function drawChart(rows){const c=$('#hash-chart'),dpr=devicePixelRatio||1,w=c.clientWidth||600,h=210;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.strokeStyle='#233044';x.lineWidth=1;for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,i*h/5);x.lineTo(w,i*h/5);x.stroke()}if(!rows.length)return;const max=Math.max(...rows.map(r=>r.total_hashrate),1);x.beginPath();rows.forEach((r,i)=>{const px=i/(Math.max(1,rows.length-1))*w,py=h-18-(r.total_hashrate/max)*(h-35);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle='#4ed7c8';x.lineWidth=2;x.stroke()}
$$('[data-copy]').forEach(b=>b.onclick=async()=>{const text=$(`#${b.dataset.copy}`).textContent;if(text==='Not configured')return;await navigator.clipboard.writeText(text);$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1400)});
async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw Error(r.status);render(await r.json())}catch(e){$('#health').className='health bad';$('#health span').textContent='Dashboard API unavailable'}}
refresh();setInterval(refresh,10000);window.addEventListener('resize',()=>loadChart());
