version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: minerwatch-discord-watchdog_server_1
      APP_PORT: 8787

  server:
    image: ghcr.io/12gaugekenshin/minerwatch-discord-watchdog:0.1.0
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    environment:
      CONFIG_PATH: /data/config.json
      CONFIG_TEMPLATE_PATH: /app/config.example.json
      WEB_UI: "true"
      WEB_PORT: "8787"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ${APP_DATA_DIR}/data:/data
